$node = <<SCRIPT
    DEBIAN_FRONTEND=noninteractive apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
    DEBIAN_FRONTEND=noninteractive apt-get install -y npm
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
  end

  config.ssh.forward_agent = true
  config.vm.network :forwarded_port, host: 38050, guest: 38050

  config.vm.provision "shell", inline: $node

end
